minio:
  auth:
    rootUser: admin
    rootPassword: Passw0rd
  persistence:
    enabled: true
    size: 20Gi
  containerPorts:
    api: 9000
    console: 8080
  service:
    ports:
      api: 9000
      console: 8080
nginx:
  service:
    type: ClusterIP
  extraVolumes:
  - name: nginx-config
    configMap:
      name: configs
  extraVolumeMounts:
  - name: nginx-config
    mountPath: /opt/bitnami/nginx/conf/nginx.conf
    subPath: nginx.conf
