minio:
  auth:
    rootUser: admin
    rootPassword: Passw0rd
  persistence:
    enabled: true
    size: 20Gi
nginx:
  service:
    type: ClusterIP
  extraVolumes:
  - name: nginx-config
    configMap:
      name: configs
  extraVolumeMounts:
  - name: nginx-config
    mountPath: /opt/bitnami/nginx/conf/nginx.conf
    subPath: nginx.conf
