minio:
  resources:
    requests:
      cpu: 4000m
      memory: 16Gi
  auth:
    rootUser: admin
    rootPassword: Passw0rd
  persistence:
    enabled: true
    size: 20Gi
  containerPorts:
    api: 9000
    console: 8080
  service:
    ports:
      api: 9000
      console: 8080
  mode: distributed
nginx:
  resources:
    requests:
      cpu: 1000m
  service:
    type: ClusterIP
  extraVolumes:
  - name: nginx-config
    configMap:
      name: configs
  extraVolumeMounts:
  - name: nginx-config
    mountPath: /opt/bitnami/nginx/conf/nginx.conf
    subPath: nginx.conf
