apiVersion: batch/v1
kind: Job
metadata:
  name: warp
  namespace: devns6
spec:
  backoffLimit: 0
  template:
    metadata:
      name: warp
    spec:
      restartPolicy: Never
      containers:
      - name: warp
        image: minio/warp:v0.7.3
        command:
        - /warp
        - get
        - --insecure
        - --host=mt-nginx
        - --access-key=admin
        - --secret-key=Passw0rd
        - --obj.size=10KiB
