apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: shell
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shell
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:jammy
        command: ["bash", "-c", "while true; do sleep 30; done;"]
